backend:
  name: git-gateway
  branch: main

media_folder: "src/images/uploads"
public_folder: "/images/uploads"

collections:
  - label: "Article"
    name: "articles"
    folder: "src/posts/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Twitter Handle",
          hint: "Your twitter handle (without the @)",
          name: "username",
          widget: "string",
        }
      - { label: "Published Date", name: "published", widget: "date" }
      - { label: "Updated Date", name: "updated", widget: "date" }
      - {
          label: "Category",
          hint: "Please refer techlyafrica.com/docs/category-tags to see how we use categories and tags.",
          name: "category",
          widget: "select",
          options:
            [
              "Programming",
              "Designing",
              "Blockchain",
              "Web Development",
              "Computers",
              "App Development",
              "Security",
              "Browsers",
              "AI",
              "Database",
              "Math",
              "Tools",
            ],
        }
      - {
          label: "Article Tags",
          hint: "Comma separated list of items. Eg: Python, Django, Web Security",
          name: "tags",
          widget: "list",
        }
      - {
          label: "Article Type",
          name: "type",
          widget: "select",
          option: ["Blog", "Tutorial", "Course", "News"],
        }
      - {
          label: "Image",
          hint: "Please convert your image to webp (.webp file extension) before uploading.",
          name: "image",
          widget: "image",
          required: false,
        }
      - {
          label: "Image Description",
          name: "caption",
          widget: "string",
          required: false,
        }
      - { label: "Article Summary", name: "summary", widget: "text" }
      - { label: "Article Body", name: "body", widget: "markdown" }

  - label: "Ebook"
    name: "ebooks"
    folder: "src/posts/ebooks"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Book Name", name: "name", widget: "string" }
      - { label: "Year Published", name: "year", widget: "string" }
      - {
          label: "Category",
          name: "category",
          widget: "relation",
          collection: "articles",
          value_field: "category.*",
          search_fields: "category.*",
          display_fields: "category.*",
        }
      - {
          label: "Article Tags",
          hint: "Comma separated list of items. Eg: Python, Django, Web Security",
          name: "tags",
          widget: "list",
        }
      - { label: "Year Published", name: "year", widget: "string" }
      - { label: "Authors", name: "authors", widget: "string" }
      - { label: "size", name: "size", widget: "string" }
      - {
          label: "Book Image",
          hint: "Please convert your image to webp (.webp file extension) before uploading.",
          name: "image",
          widget: "image",
        }
      - { label: "Image Description", name: "caption", widget: "string" }
      - { label: "Upload Book", name: "file", widget: "file" }
      - {
          label: "EBook Format",
          name: "format",
          widget: "select",
          option: ["PDF", "EBUD"],
        }
      - { label: "ISBN", name: "isbn", widget: "string" }
      - { label: "Book Name", name: "name", widget: "string" }
      - { label: "Book Name", name: "name", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown" }

  - label: "Data files"
    name: "data"
    files:
      - label: "Author Info"
        name: "authors"
        file: "src/_data/authors.json"
        fields:
          - label: "Twitter Username"
            name: "title"
            widget: list
            fields:
              - { label: "Author Full Name", name: "name", widget: "string" }
              - { label: "Email Address", name: "email", widget: "string" }
              - {
                  label: "Twitter",
                  name: "twitter",
                  widget: "hidden",
                  default: "{{title}}",
                }
              - {
                  label: "Website",
                  hint: "Eg, website.com (without the protocol).",
                  name: "website",
                  widget: "string",
                  required: false,
                }
              - {
                  label: "Avatar",
                  hint: "Please convert your image to webp (.webp file extension) before uploading.",
                  name: "avatar",
                  widget: "image",
                }
              - { label: "Author Bio", name: "bio", widget: "text" }
